language: r

dist: xenial
sudo: true
warnings_are_errors: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
      - libpython3.6-dev
      - python3.6-venv

before_install:
  - sudo ln -sf /usr/bin/python3.6 /usr/bin/python
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo -H python get-pip.py > /dev/null
  - pip install --upgrade --ignore-installed --user travis virtualenv > /dev/null

r_packages: reticulate

before_script:
  - R CMD INSTALL . > /dev/null
  - R -e 'keras::install_keras()'
