# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip

install:
  - pip install --upgrade pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv

before_script:
  - R CMD INSTALL .
  - R -e 'Sys.setenv(PIP_QUIET=1); keras::install_keras()'
  - R -e 'tensorflow::tf_config()'
